export const COUNTRIES = [
  {
    code: "ad",
    name: "Andorra",
    continent: "Europe",
    difficulty: "hard",
    description: "Vertical tricolor of blue, yellow, and red with a coat of arms in the center",
  },
  {
    code: "ae",
    name: "United Arab Emirates",
    continent: "Asia",
    difficulty: "medium",
    description: "Three horizontal stripes of green, white, and black with a vertical red band on the hoist side",
  },
  {
    code: "af",
    name: "Afghanistan",
    continent: "Asia",
    difficulty: "medium",
    description: "Vertical tricolor of black, red, and green with a white emblem in the center",
  },
  {
    code: "ag",
    name: "Antigua and Barbuda",
    continent: "North America",
    difficulty: "hard",
    description: "Red background with inverted V-shaped black, blue, and white bands, with a rising sun symbol",
  },
  {
    code: "al",
    name: "Albania",
    continent: "Europe",
    difficulty: "medium",
    description: "Red background with a black double-headed eagle in the center",
  },
  {
    code: "am",
    name: "Armenia",
    continent: "Asia",
    difficulty: "medium",
    description: "Three horizontal stripes of red, blue, and orange",
  },
  {
    code: "ao",
    name: "Angola",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal red and black stripes with a yellow emblem featuring a machete, star, and gear",
  },
  {
    code: "ar",
    name: "Argentina",
    continent: "South America",
    difficulty: "easy",
    description: "Horizontal stripes of light blue, white, and light blue with a golden sun in the center",
  },
  {
    code: "at",
    name: "Austria",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of red, white, and red",
  },
  {
    code: "au",
    name: "Australia",
    continent: "Oceania",
    difficulty: "easy",
    description: "Blue background with Union Jack in the corner and white stars including the Southern Cross",
  },
  {
    code: "az",
    name: "Azerbaijan",
    continent: "Asia",
    difficulty: "medium",
    description: "Three horizontal stripes of blue, red, and green with a white crescent and star",
  },
  {
    code: "ba",
    name: "Bosnia and Herzegovina",
    continent: "Europe",
    difficulty: "hard",
    description: "Blue background with yellow diagonal band and white stars along the band",
  },
  {
    code: "bb",
    name: "Barbados",
    continent: "North America",
    difficulty: "medium",
    description: "Vertical stripes of blue, yellow, and blue with a black trident head in the center",
  },
  {
    code: "bd",
    name: "Bangladesh",
    continent: "Asia",
    difficulty: "medium",
    description: "Green background with a red circle slightly off-center to the hoist",
  },
  {
    code: "be",
    name: "Belgium",
    continent: "Europe",
    difficulty: "easy",
    description: "Vertical tricolor of black, yellow, and red",
  },
  {
    code: "bf",
    name: "Burkina Faso",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal red and green stripes with a yellow star in the center",
  },
  {
    code: "bg",
    name: "Bulgaria",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of white, green, and red",
  },
  {
    code: "bh",
    name: "Bahrain",
    continent: "Asia",
    difficulty: "hard",
    description: "White and red divided by a serrated line with five triangular points",
  },
  {
    code: "bi",
    name: "Burundi",
    continent: "Africa",
    difficulty: "hard",
    description: "White X dividing red and green quarters with three red stars in a white circle at center",
  },
  {
    code: "bj",
    name: "Benin",
    continent: "Africa",
    difficulty: "hard",
    description: "Vertical green stripe on left, with yellow and red horizontal stripes on right",
  },
  {
    code: "bn",
    name: "Brunei",
    continent: "Asia",
    difficulty: "hard",
    description: "Yellow background with white and black diagonal stripes and a red crest in the center",
  },
  {
    code: "bo",
    name: "Bolivia",
    continent: "South America",
    difficulty: "medium",
    description: "Three horizontal stripes of red, yellow, and green with a coat of arms in the center",
  },
  {
    code: "br",
    name: "Brazil",
    continent: "South America",
    difficulty: "easy",
    description: "Green background with yellow diamond and blue circle containing white stars and a banner",
  },
  {
    code: "bs",
    name: "Bahamas",
    continent: "North America",
    difficulty: "medium",
    description: "Three horizontal stripes of aquamarine, yellow, and aquamarine with a black triangle on the hoist",
  },
  {
    code: "bt",
    name: "Bhutan",
    continent: "Asia",
    difficulty: "hard",
    description: "Diagonal orange and yellow halves with a white dragon in the center",
  },
  {
    code: "bw",
    name: "Botswana",
    continent: "Africa",
    difficulty: "medium",
    description: "Light blue background with a black horizontal stripe bordered by two thin white stripes",
  },
  {
    code: "by",
    name: "Belarus",
    continent: "Europe",
    difficulty: "medium",
    description: "Red and green horizontal stripes with an ornamental pattern on the hoist side",
  },
  {
    code: "bz",
    name: "Belize",
    continent: "North America",
    difficulty: "hard",
    description: "Blue background with red stripes on top and bottom edges and a circular emblem in the center",
  },
  {
    code: "ca",
    name: "Canada",
    continent: "North America",
    difficulty: "easy",
    description: "Red vertical stripes on the sides with a white center featuring a red maple leaf",
  },
  {
    code: "cd",
    name: "DR Congo",
    continent: "Africa",
    difficulty: "medium",
    description: "Light blue background with a yellow star and a red diagonal stripe bordered by yellow",
  },
  {
    code: "cf",
    name: "Central African Republic",
    continent: "Africa",
    difficulty: "hard",
    description: "Four horizontal stripes of blue, white, green, and yellow with a red vertical stripe and yellow star",
  },
  {
    code: "cg",
    name: "Congo",
    continent: "Africa",
    difficulty: "hard",
    description: "Diagonal green, yellow, and red stripes from corner to corner",
  },
  {
    code: "ch",
    name: "Switzerland",
    continent: "Europe",
    difficulty: "easy",
    description: "Red background with a white cross in the center",
  },
  {
    code: "ci",
    name: "Ivory Coast",
    continent: "Africa",
    difficulty: "hard",
    description: "Vertical tricolor of orange, white, and green",
  },
  {
    code: "cl",
    name: "Chile",
    continent: "South America",
    difficulty: "easy",
    description: "Blue square with white star in top left, white stripe on top, red stripe on bottom",
  },
  {
    code: "cm",
    name: "Cameroon",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical tricolor of green, red, and yellow with a yellow star in the center",
  },
  {
    code: "cn",
    name: "China",
    continent: "Asia",
    difficulty: "easy",
    description: "Red background with five yellow stars in the top left corner, one large and four small",
  },
  {
    code: "co",
    name: "Colombia",
    continent: "South America",
    difficulty: "medium",
    description: "Three horizontal stripes of yellow (half), blue, and red",
  },
  {
    code: "cr",
    name: "Costa Rica",
    continent: "North America",
    difficulty: "medium",
    description: "Five horizontal stripes of blue, white, red (wider), white, and blue",
  },
  {
    code: "cu",
    name: "Cuba",
    continent: "North America",
    difficulty: "medium",
    description: "Five horizontal stripes alternating blue and white with a red triangle and white star on the hoist",
  },
  {
    code: "cv",
    name: "Cape Verde",
    continent: "Africa",
    difficulty: "hard",
    description: "Blue background with white and red horizontal stripes and a circle of yellow stars",
  },
  {
    code: "cy",
    name: "Cyprus",
    continent: "Europe",
    difficulty: "medium",
    description: "White background with an orange silhouette of the island and olive branches below",
  },
  {
    code: "cz",
    name: "Czechia",
    continent: "Europe",
    difficulty: "medium",
    description: "White and red horizontal stripes with a blue triangle on the hoist side",
  },
  {
    code: "de",
    name: "Germany",
    continent: "Europe",
    difficulty: "easy",
    description: "Three horizontal stripes of black, red, and gold",
  },
  {
    code: "dj",
    name: "Djibouti",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal light blue and light green stripes with a white triangle and red star on the hoist",
  },
  {
    code: "dk",
    name: "Denmark",
    continent: "Europe",
    difficulty: "easy",
    description: "Red background with a white Nordic cross shifted to the hoist side",
  },
  {
    code: "dm",
    name: "Dominica",
    continent: "North America",
    difficulty: "hard",
    description: "Green background with crosses forming quarters, and a red circle with a parrot in the center",
  },
  {
    code: "do",
    name: "Dominican Republic",
    continent: "North America",
    difficulty: "medium",
    description: "Quartered red and blue with a white cross and a coat of arms in the center",
  },
  {
    code: "dz",
    name: "Algeria",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical halves of green and white with a red crescent and star in the center",
  },
  {
    code: "ec",
    name: "Ecuador",
    continent: "South America",
    difficulty: "medium",
    description: "Three horizontal stripes of yellow (half), blue, and red with a coat of arms in the center",
  },
  {
    code: "ee",
    name: "Estonia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of blue, black, and white",
  },
  {
    code: "eg",
    name: "Egypt",
    continent: "Africa",
    difficulty: "easy",
    description: "Three horizontal stripes of red, white, and black with a golden eagle in the center",
  },
  {
    code: "er",
    name: "Eritrea",
    continent: "Africa",
    difficulty: "hard",
    description:
      "Red triangle on the hoist with green and blue triangular sections and a yellow wreath and olive branch",
  },
  {
    code: "es",
    name: "Spain",
    continent: "Europe",
    difficulty: "easy",
    description: "Three horizontal stripes of red, yellow (wider), and red with a coat of arms",
  },
  {
    code: "et",
    name: "Ethiopia",
    continent: "Africa",
    difficulty: "medium",
    description: "Three horizontal stripes of green, yellow, and red with a blue circle and yellow star emblem",
  },
  {
    code: "fi",
    name: "Finland",
    continent: "Europe",
    difficulty: "easy",
    description: "White background with a blue Nordic cross shifted to the hoist side",
  },
  {
    code: "fj",
    name: "Fiji",
    continent: "Oceania",
    difficulty: "hard",
    description: "Light blue background with Union Jack in corner and a shield with a red cross",
  },
  {
    code: "fm",
    name: "Micronesia",
    continent: "Oceania",
    difficulty: "hard",
    description: "Light blue background with four white stars arranged in a diamond pattern",
  },
  {
    code: "fr",
    name: "France",
    continent: "Europe",
    difficulty: "easy",
    description: "Vertical tricolor of blue, white, and red",
  },
  {
    code: "ga",
    name: "Gabon",
    continent: "Africa",
    difficulty: "hard",
    description: "Three horizontal stripes of green, yellow, and blue",
  },
  {
    code: "gb",
    name: "United Kingdom",
    continent: "Europe",
    difficulty: "easy",
    description: "Blue background with red and white crosses forming the Union Jack",
  },
  {
    code: "gd",
    name: "Grenada",
    continent: "North America",
    difficulty: "hard",
    description: "Red border with yellow stars, green and yellow triangles inside, and a nutmeg symbol",
  },
  {
    code: "ge",
    name: "Georgia",
    continent: "Asia",
    difficulty: "medium",
    description: "White background with a large red cross and four small red crosses in each quadrant",
  },
  {
    code: "gh",
    name: "Ghana",
    continent: "Africa",
    difficulty: "medium",
    description: "Three horizontal stripes of red, yellow, and green with a black star in the center",
  },
  {
    code: "gm",
    name: "Gambia",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal stripes of red, blue, and green separated by thin white stripes",
  },
  {
    code: "gn",
    name: "Guinea",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical tricolor of red, yellow, and green",
  },
  {
    code: "gq",
    name: "Equatorial Guinea",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal green, white, and red stripes with a blue triangle on the hoist and a coat of arms",
  },
  {
    code: "gr",
    name: "Greece",
    continent: "Europe",
    difficulty: "easy",
    description: "Blue and white horizontal stripes with a blue square containing a white cross in the corner",
  },
  {
    code: "gt",
    name: "Guatemala",
    continent: "North America",
    difficulty: "medium",
    description: "Three vertical stripes of light blue, white, and light blue with a coat of arms in the center",
  },
  {
    code: "gw",
    name: "Guinea-Bissau",
    continent: "Africa",
    difficulty: "hard",
    description: "Vertical red stripe on the hoist with horizontal yellow and green stripes and a black star",
  },
  {
    code: "gy",
    name: "Guyana",
    continent: "South America",
    difficulty: "hard",
    description: "Green background with yellow triangle bordered by white, containing a red triangle bordered by black",
  },
  {
    code: "hn",
    name: "Honduras",
    continent: "North America",
    difficulty: "medium",
    description: "Three horizontal stripes of blue, white, and blue with five blue stars in the center",
  },
  {
    code: "hr",
    name: "Croatia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of red, white, and blue with a checkered coat of arms in the center",
  },
  {
    code: "ht",
    name: "Haiti",
    continent: "North America",
    difficulty: "medium",
    description: "Horizontal blue and red stripes with a coat of arms featuring a palm tree in the center",
  },
  {
    code: "hu",
    name: "Hungary",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of red, white, and green",
  },
  {
    code: "id",
    name: "Indonesia",
    continent: "Asia",
    difficulty: "hard",
    description: "Two horizontal stripes of red and white",
  },
  {
    code: "ie",
    name: "Ireland",
    continent: "Europe",
    difficulty: "easy",
    description: "Vertical tricolor of green, white, and orange",
  },
  {
    code: "il",
    name: "Israel",
    continent: "Asia",
    difficulty: "easy",
    description: "White background with two horizontal blue stripes and a blue Star of David in the center",
  },
  {
    code: "in",
    name: "India",
    continent: "Asia",
    difficulty: "easy",
    description: "Three horizontal stripes of saffron, white, and green with a blue wheel in the center",
  },
  {
    code: "iq",
    name: "Iraq",
    continent: "Asia",
    difficulty: "medium",
    description: "Three horizontal stripes of red, white, and black with green Arabic text in the center",
  },
  {
    code: "ir",
    name: "Iran",
    continent: "Asia",
    difficulty: "medium",
    description: "Three horizontal stripes of green, white, and red with a red emblem in the center",
  },
  {
    code: "is",
    name: "Iceland",
    continent: "Europe",
    difficulty: "easy",
    description: "Blue background with a red Nordic cross outlined in white shifted to the hoist side",
  },
  {
    code: "it",
    name: "Italy",
    continent: "Europe",
    difficulty: "easy",
    description: "Vertical tricolor of green, white, and red",
  },
  {
    code: "jm",
    name: "Jamaica",
    continent: "North America",
    difficulty: "medium",
    description: "Gold diagonal cross dividing the flag into green triangles at top and bottom and black at sides",
  },
  {
    code: "jo",
    name: "Jordan",
    continent: "Asia",
    difficulty: "hard",
    description: "Horizontal black, white, and green stripes with a red triangle on the hoist featuring a white star",
  },
  {
    code: "jp",
    name: "Japan",
    continent: "Asia",
    difficulty: "easy",
    description: "White background with a large red circle in the center",
  },
  {
    code: "ke",
    name: "Kenya",
    continent: "Africa",
    difficulty: "medium",
    description:
      "Horizontal black, red, and green stripes with white borders and a Maasai shield with spears in center",
  },
  {
    code: "kg",
    name: "Kyrgyzstan",
    continent: "Asia",
    difficulty: "hard",
    description: "Red background with a yellow sun containing a red circular pattern in the center",
  },
  {
    code: "kh",
    name: "Cambodia",
    continent: "Asia",
    difficulty: "medium",
    description: "Red with blue stripes on top and bottom edges and a white temple (Angkor Wat) in the center",
  },
  {
    code: "ki",
    name: "Kiribati",
    continent: "Oceania",
    difficulty: "hard",
    description: "Red background with wavy white and blue stripes at bottom and a yellow sun with a bird over it",
  },
  {
    code: "km",
    name: "Comoros",
    continent: "Africa",
    difficulty: "hard",
    description:
      "Four horizontal stripes of yellow, white, red, and blue with a green triangle and white crescent and stars",
  },
  {
    code: "kn",
    name: "Saint Kitts and Nevis",
    continent: "North America",
    difficulty: "hard",
    description: "Diagonal black band with two white stars bordered by yellow, with green and red triangles",
  },
  {
    code: "kp",
    name: "North Korea",
    continent: "Asia",
    difficulty: "medium",
    description: "Blue stripes on top and bottom, wide red stripe in center with a white circle containing a red star",
  },
  {
    code: "kr",
    name: "South Korea",
    continent: "Asia",
    difficulty: "easy",
    description: "White background with a red and blue yin-yang symbol and four black trigrams in the corners",
  },
  {
    code: "kw",
    name: "Kuwait",
    continent: "Asia",
    difficulty: "hard",
    description: "Horizontal green, white, and red stripes with a black trapezoid on the hoist",
  },
  {
    code: "kz",
    name: "Kazakhstan",
    continent: "Asia",
    difficulty: "medium",
    description: "Light blue background with a yellow sun and eagle in the center and ornamental pattern on hoist",
  },
  {
    code: "la",
    name: "Laos",
    continent: "Asia",
    difficulty: "hard",
    description: "Three horizontal stripes of red, blue (wider), and red with a white circle in the center",
  },
  {
    code: "lb",
    name: "Lebanon",
    continent: "Asia",
    difficulty: "hard",
    description: "Three horizontal stripes of red, white (wider), and red with a green cedar tree in the center",
  },
  {
    code: "lc",
    name: "Saint Lucia",
    continent: "North America",
    difficulty: "hard",
    description: "Light blue background with a gold and black triangular design in the center",
  },
  {
    code: "li",
    name: "Liechtenstein",
    continent: "Europe",
    difficulty: "hard",
    description: "Horizontal blue and red stripes with a gold crown in the top left corner",
  },
  {
    code: "lk",
    name: "Sri Lanka",
    continent: "Asia",
    difficulty: "medium",
    description: "Green and orange vertical stripes on left, maroon field with yellow lion holding a sword and leaves",
  },
  {
    code: "lr",
    name: "Liberia",
    continent: "Africa",
    difficulty: "hard",
    description: "Red and white horizontal stripes with a blue square containing a white star in the corner",
  },
  {
    code: "ls",
    name: "Lesotho",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal blue, white, and green stripes with a black traditional hat in the center",
  },
  {
    code: "lt",
    name: "Lithuania",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of yellow, green, and red",
  },
  {
    code: "lu",
    name: "Luxembourg",
    continent: "Europe",
    difficulty: "hard",
    description: "Three horizontal stripes of red, white, and light blue",
  },
  {
    code: "lv",
    name: "Latvia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of dark red, white (narrower), and dark red",
  },
  {
    code: "ly",
    name: "Libya",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal red, black, and green stripes with a white crescent and star in the center",
  },
  {
    code: "ma",
    name: "Morocco",
    continent: "Africa",
    difficulty: "medium",
    description: "Red background with a green star in the center",
  },
  {
    code: "mc",
    name: "Monaco",
    continent: "Europe",
    difficulty: "hard",
    description: "Two horizontal stripes of red and white",
  },
  {
    code: "md",
    name: "Moldova",
    continent: "Europe",
    difficulty: "hard",
    description: "Vertical tricolor of blue, yellow, and red with a coat of arms in the center",
  },
  {
    code: "me",
    name: "Montenegro",
    continent: "Europe",
    difficulty: "medium",
    description: "Red background with a golden double-headed eagle and a coat of arms in the center",
  },
  {
    code: "mg",
    name: "Madagascar",
    continent: "Africa",
    difficulty: "medium",
    description: "White vertical stripe on left with horizontal red and green stripes on right",
  },
  {
    code: "mh",
    name: "Marshall Islands",
    continent: "Oceania",
    difficulty: "hard",
    description: "Blue background with diagonal orange and white stripes and a white star in the corner",
  },
  {
    code: "mk",
    name: "North Macedonia",
    continent: "Europe",
    difficulty: "medium",
    description: "Red background with a yellow sun with eight rays extending to the edges",
  },
  {
    code: "ml",
    name: "Mali",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical tricolor of green, yellow, and red",
  },
  {
    code: "mm",
    name: "Myanmar",
    continent: "Asia",
    difficulty: "medium",
    description: "Horizontal yellow, green, and red stripes with a large white star in the center",
  },
  {
    code: "mn",
    name: "Mongolia",
    continent: "Asia",
    difficulty: "medium",
    description: "Vertical red, blue, and red stripes with a yellow symbol on the hoist stripe",
  },
  {
    code: "mr",
    name: "Mauritania",
    continent: "Africa",
    difficulty: "hard",
    description: "Green background with a yellow crescent and star, bordered by red stripes on top and bottom",
  },
  {
    code: "mt",
    name: "Malta",
    continent: "Europe",
    difficulty: "hard",
    description: "Vertical halves of white and red with a George Cross in the corner",
  },
  {
    code: "mu",
    name: "Mauritius",
    continent: "Africa",
    difficulty: "hard",
    description: "Four horizontal stripes of red, blue, yellow, and green",
  },
  {
    code: "mv",
    name: "Maldives",
    continent: "Asia",
    difficulty: "hard",
    description: "Red background with a green rectangle containing a white crescent in the center",
  },
  {
    code: "mw",
    name: "Malawi",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal black, red, and green stripes with a red rising sun on the top stripe",
  },
  {
    code: "mx",
    name: "Mexico",
    continent: "North America",
    difficulty: "easy",
    description: "Vertical tricolor of green, white, and red with an eagle on a cactus in the center",
  },
  {
    code: "my",
    name: "Malaysia",
    continent: "Asia",
    difficulty: "medium",
    description: "Red and white horizontal stripes with a blue canton containing a yellow crescent and star",
  },
  {
    code: "mz",
    name: "Mozambique",
    continent: "Africa",
    difficulty: "hard",
    description:
      "Horizontal green, black, and yellow stripes with white borders and a red triangle with a star and rifle",
  },
  {
    code: "na",
    name: "Namibia",
    continent: "Africa",
    difficulty: "medium",
    description:
      "Diagonal red stripe bordered by white from bottom left to top right, blue and green triangles, with yellow sun",
  },
  {
    code: "ne",
    name: "Niger",
    continent: "Africa",
    difficulty: "hard",
    description: "Three horizontal stripes of orange, white, and green with an orange circle in the center",
  },
  {
    code: "ng",
    name: "Nigeria",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical tricolor of green, white, and green",
  },
  {
    code: "ni",
    name: "Nicaragua",
    continent: "North America",
    difficulty: "hard",
    description: "Three horizontal stripes of blue, white, and blue with a coat of arms in the center",
  },
  {
    code: "nl",
    name: "Netherlands",
    continent: "Europe",
    difficulty: "easy",
    description: "Three horizontal stripes of red, white, and blue",
  },
  {
    code: "no",
    name: "Norway",
    continent: "Europe",
    difficulty: "easy",
    description: "Red background with a blue Nordic cross outlined in white shifted to the hoist side",
  },
  {
    code: "np",
    name: "Nepal",
    continent: "Asia",
    difficulty: "medium",
    description: "Two stacked triangular pennants in red with blue border, containing white moon and sun symbols",
  },
  {
    code: "nr",
    name: "Nauru",
    continent: "Oceania",
    difficulty: "hard",
    description: "Blue background with a yellow horizontal stripe and white star below the stripe on the left",
  },
  {
    code: "nz",
    name: "New Zealand",
    continent: "Oceania",
    difficulty: "easy",
    description:
      "Blue background with Union Jack in corner and four red stars with white borders forming the Southern Cross",
  },
  {
    code: "om",
    name: "Oman",
    continent: "Asia",
    difficulty: "hard",
    description:
      "Horizontal white, red, and green stripes with a red vertical band featuring a white emblem on the hoist",
  },
  {
    code: "pa",
    name: "Panama",
    continent: "North America",
    difficulty: "medium",
    description: "Four quarters with white squares containing blue and red stars, and solid blue and red squares",
  },
  {
    code: "pe",
    name: "Peru",
    continent: "South America",
    difficulty: "medium",
    description: "Vertical tricolor of red, white, and red with a coat of arms in the center",
  },
  {
    code: "pg",
    name: "Papua New Guinea",
    continent: "Oceania",
    difficulty: "medium",
    description: "Diagonal division from top left to bottom right with red and black, bird of paradise and stars",
  },
  {
    code: "ph",
    name: "Philippines",
    continent: "Asia",
    difficulty: "medium",
    description: "Horizontal blue and red stripes with white triangle on hoist containing a sun and three stars",
  },
  {
    code: "pk",
    name: "Pakistan",
    continent: "Asia",
    difficulty: "medium",
    description: "Green background with a white vertical band on the hoist, white crescent and star on green",
  },
  {
    code: "pl",
    name: "Poland",
    continent: "Europe",
    difficulty: "medium",
    description: "Two horizontal stripes of white and red",
  },
  {
    code: "pt",
    name: "Portugal",
    continent: "Europe",
    difficulty: "easy",
    description: "Vertical green and red stripes with the armillary sphere and shield coat of arms at the junction",
  },
  {
    code: "pw",
    name: "Palau",
    continent: "Oceania",
    difficulty: "hard",
    description: "Light blue background with a large yellow circle slightly off-center to the hoist",
  },
  {
    code: "py",
    name: "Paraguay",
    continent: "South America",
    difficulty: "hard",
    description: "Three horizontal stripes of red, white, and blue with a coat of arms in the center",
  },
  {
    code: "qa",
    name: "Qatar",
    continent: "Asia",
    difficulty: "medium",
    description: "Maroon background with a white serrated band on the hoist side with nine points",
  },
  {
    code: "ro",
    name: "Romania",
    continent: "Europe",
    difficulty: "medium",
    description: "Vertical tricolor of blue, yellow, and red",
  },
  {
    code: "rs",
    name: "Serbia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of red, blue, and white with a coat of arms on the left side",
  },
  {
    code: "ru",
    name: "Russia",
    continent: "Europe",
    difficulty: "easy",
    description: "Three horizontal stripes of white, blue, and red",
  },
  {
    code: "rw",
    name: "Rwanda",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal blue, yellow, and green stripes with a yellow sun in the upper right corner",
  },
  {
    code: "sa",
    name: "Saudi Arabia",
    continent: "Asia",
    difficulty: "easy",
    description: "Green background with white Arabic text and a sword below it",
  },
  {
    code: "sb",
    name: "Solomon Islands",
    continent: "Oceania",
    difficulty: "hard",
    description: "Diagonal yellow stripe from bottom left to top right dividing blue and green with five white stars",
  },
  {
    code: "sc",
    name: "Seychelles",
    continent: "Africa",
    difficulty: "hard",
    description: "Five radiating bands of blue, yellow, red, white, and green from the bottom left corner",
  },
  {
    code: "sd",
    name: "Sudan",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal red, white, and black stripes with a green triangle on the hoist",
  },
  {
    code: "se",
    name: "Sweden",
    continent: "Europe",
    difficulty: "easy",
    description: "Blue background with a yellow Nordic cross shifted to the hoist side",
  },
  {
    code: "sg",
    name: "Singapore",
    continent: "Asia",
    difficulty: "medium",
    description: "Horizontal red and white stripes with a white crescent and five stars in the corner",
  },
  {
    code: "si",
    name: "Slovenia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of white, blue, and red with a coat of arms in the corner",
  },
  {
    code: "sk",
    name: "Slovakia",
    continent: "Europe",
    difficulty: "medium",
    description: "Three horizontal stripes of white, blue, and red with a coat of arms on the left",
  },
  {
    code: "sl",
    name: "Sierra Leone",
    continent: "Africa",
    difficulty: "hard",
    description: "Three horizontal stripes of green, white, and blue",
  },
  {
    code: "sm",
    name: "San Marino",
    continent: "Europe",
    difficulty: "hard",
    description: "Horizontal white and light blue stripes with a coat of arms in the center",
  },
  {
    code: "sn",
    name: "Senegal",
    continent: "Africa",
    difficulty: "medium",
    description: "Vertical tricolor of green, yellow, and red with a green star in the center",
  },
  {
    code: "so",
    name: "Somalia",
    continent: "Africa",
    difficulty: "medium",
    description: "Light blue background with a white star in the center",
  },
  {
    code: "sr",
    name: "Suriname",
    continent: "South America",
    difficulty: "hard",
    description: "Horizontal green, white, red, white, and green stripes with a yellow star in the center",
  },
  {
    code: "ss",
    name: "South Sudan",
    continent: "Africa",
    difficulty: "hard",
    description:
      "Horizontal black, red, and green stripes with white borders and a blue triangle with yellow star on hoist",
  },
  {
    code: "st",
    name: "Sao Tome and Principe",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal green, yellow, and green stripes with a red triangle on hoist and two black stars",
  },
  {
    code: "sv",
    name: "El Salvador",
    continent: "North America",
    difficulty: "medium",
    description: "Three horizontal stripes of blue, white, and blue with a coat of arms in the center",
  },
  {
    code: "sy",
    name: "Syria",
    continent: "Asia",
    difficulty: "hard",
    description: "Horizontal red, white, and black stripes with two green stars in the center white stripe",
  },
  {
    code: "sz",
    name: "Eswatini",
    continent: "Africa",
    difficulty: "hard",
    description: "Horizontal blue, yellow, red, yellow, and blue stripes with a black and white shield and weapons",
  },
  {
    code: "td",
    name: "Chad",
    continent: "Africa",
    difficulty: "hard",
    description: "Vertical tricolor of blue, yellow, and red",
  },
  {
    code: "tg",
    name: "Togo",
    continent: "Africa",
    difficulty: "hard",
    description:
      "Five horizontal stripes alternating green and yellow with a red square containing a white star in corner",
  },
  {
    code: "th",
    name: "Thailand",
    continent: "Asia",
    difficulty: "easy",
    description: "Five horizontal stripes of red, white, blue (wider), white, and red",
  },
  {
    code: "tj",
    name: "Tajikistan",
    continent: "Asia",
    difficulty: "hard",
    description: "Horizontal red, white, and green stripes with a crown and stars in the center",
  },
  {
    code: "tl",
    name: "Timor-Leste",
    continent: "Asia",
    difficulty: "hard",
    description: "Red background with yellow triangle on hoist containing a black triangle with a white star",
  },
  {
    code: "tm",
    name: "Turkmenistan",
    continent: "Asia",
    difficulty: "hard",
    description: "Green background with a red vertical stripe featuring carpet patterns and a crescent with stars",
  },
  {
    code: "tn",
    name: "Tunisia",
    continent: "Africa",
    difficulty: "medium",
    description: "Red background with a white circle containing a red crescent and star",
  },
  {
    code: "to",
    name: "Tonga",
    continent: "Oceania",
    difficulty: "hard",
    description: "Red background with a white rectangle in the corner containing a red cross",
  },
  {
    code: "tr",
    name: "Turkey",
    continent: "Asia",
    difficulty: "easy",
    description: "Red background with a white crescent and star",
  },
  {
    code: "tt",
    name: "Trinidad and Tobago",
    continent: "North America",
    difficulty: "medium",
    description: "Red background with a black diagonal stripe bordered by white from top left to bottom right",
  },
  {
    code: "tv",
    name: "Tuvalu",
    continent: "Oceania",
    difficulty: "hard",
    description: "Light blue background with Union Jack in corner and nine yellow stars representing islands",
  },
  {
    code: "tw",
    name: "Taiwan",
    continent: "Asia",
    difficulty: "medium",
    description: "Red background with a blue canton containing a white sun with twelve rays",
  },
  {
    code: "tz",
    name: "Tanzania",
    continent: "Africa",
    difficulty: "medium",
    description: "Diagonal yellow stripe bordered by black from bottom left to top right, green and blue triangles",
  },
  {
    code: "ua",
    name: "Ukraine",
    continent: "Europe",
    difficulty: "easy",
    description: "Two horizontal stripes of blue and yellow",
  },
  {
    code: "ug",
    name: "Uganda",
    continent: "Africa",
    difficulty: "medium",
    description:
      "Six horizontal stripes of black, yellow, and red repeated with a white circle containing a crested crane",
  },
  {
    code: "us",
    name: "United States",
    continent: "North America",
    difficulty: "easy",
    description: "Red and white horizontal stripes with a blue canton containing white stars",
  },
  {
    code: "uy",
    name: "Uruguay",
    continent: "South America",
    difficulty: "medium",
    description: "White and blue horizontal stripes with a white square in corner containing a yellow sun",
  },
  {
    code: "uz",
    name: "Uzbekistan",
    continent: "Asia",
    difficulty: "hard",
    description: "Horizontal blue, white, and green stripes with red borders, crescent and stars in top left",
  },
  {
    code: "va",
    name: "Vatican City",
    continent: "Europe",
    difficulty: "medium",
    description: "Vertical halves of yellow and white with the papal tiara and crossed keys",
  },
  {
    code: "vc",
    name: "Saint Vincent and the Grenadines",
    continent: "North America",
    difficulty: "hard",
    description: "Vertical stripes of blue, yellow, and green with three green diamonds arranged in a V in the center",
  },
  {
    code: "ve",
    name: "Venezuela",
    continent: "South America",
    difficulty: "medium",
    description: "Three horizontal stripes of yellow, blue, and red with an arc of eight white stars in the center",
  },
  {
    code: "vn",
    name: "Vietnam",
    continent: "Asia",
    difficulty: "medium",
    description: "Red background with a large yellow star in the center",
  },
  {
    code: "vu",
    name: "Vanuatu",
    continent: "Oceania",
    difficulty: "hard",
    description:
      "Horizontal red and green sections divided by a yellow Y-shape with black borders and a boar tusk emblem",
  },
  {
    code: "ws",
    name: "Samoa",
    continent: "Oceania",
    difficulty: "hard",
    description: "Red background with a blue canton containing five white stars of the Southern Cross",
  },
  {
    code: "ye",
    name: "Yemen",
    continent: "Asia",
    difficulty: "hard",
    description: "Three horizontal stripes of red, white, and black",
  },
  {
    code: "za",
    name: "South Africa",
    continent: "Africa",
    difficulty: "easy",
    description: "Horizontal Y-shape in green with black borders separating red, blue, white, and yellow sections",
  },
  {
    code: "zm",
    name: "Zambia",
    continent: "Africa",
    difficulty: "medium",
    description:
      "Green background with an orange eagle over three vertical stripes of red, black, and orange in the corner",
  },
  {
    code: "zw",
    name: "Zimbabwe",
    continent: "Africa",
    difficulty: "medium",
    description:
      "Horizontal green, yellow, red, black, red, yellow, and green stripes with white triangle containing Zimbabwe bird on red star",
  },
];

const CAPITALS = {
  ad: "Andorra la Vella",
  ae: "Abu Dhabi",
  af: "Kabul",
  ag: "Saint John's",
  al: "Tirana",
  am: "Yerevan",
  ao: "Luanda",
  ar: "Buenos Aires",
  at: "Vienna",
  au: "Canberra",
  az: "Baku",
  ba: "Sarajevo",
  bb: "Bridgetown",
  bd: "Dhaka",
  be: "Brussels",
  bf: "Ouagadougou",
  bg: "Sofia",
  bh: "Manama",
  bi: "Gitega",
  bj: "Porto-Novo",
  bn: "Bandar Seri Begawan",
  bo: "Sucre",
  br: "Brasília",
  bs: "Nassau",
  bt: "Thimphu",
  bw: "Gaborone",
  by: "Minsk",
  bz: "Belmopan",
  ca: "Ottawa",
  cd: "Kinshasa",
  cf: "Bangui",
  cg: "Brazzaville",
  ch: "Bern",
  ci: "Yamoussoukro",
  cl: "Santiago",
  cm: "Yaoundé",
  cn: "Beijing",
  co: "Bogotá",
  cr: "San José",
  cu: "Havana",
  cv: "Praia",
  cy: "Nicosia",
  cz: "Prague",
  de: "Berlin",
  dj: "Djibouti",
  dk: "Copenhagen",
  dm: "Roseau",
  do: "Santo Domingo",
  dz: "Algiers",
  ec: "Quito",
  ee: "Tallinn",
  eg: "Cairo",
  er: "Asmara",
  es: "Madrid",
  et: "Addis Ababa",
  fi: "Helsinki",
  fj: "Suva",
  fm: "Palikir",
  fr: "Paris",
  ga: "Libreville",
  gb: "London",
  gd: "St. George's",
  ge: "Tbilisi",
  gh: "Accra",
  gm: "Banjul",
  gn: "Conakry",
  gq: "Malabo",
  gr: "Athens",
  gt: "Guatemala City",
  gw: "Bissau",
  gy: "Georgetown",
  hn: "Tegucigalpa",
  hr: "Zagreb",
  ht: "Port-au-Prince",
  hu: "Budapest",
  id: "Jakarta",
  ie: "Dublin",
  il: "Jerusalem",
  in: "New Delhi",
  iq: "Baghdad",
  ir: "Tehran",
  is: "Reykjavik",
  it: "Rome",
  jm: "Kingston",
  jo: "Amman",
  jp: "Tokyo",
  ke: "Nairobi",
  kg: "Bishkek",
  kh: "Phnom Penh",
  ki: "South Tarawa",
  km: "Moroni",
  kn: "Basseterre",
  kp: "Pyongyang",
  kr: "Seoul",
  kw: "Kuwait City",
  kz: "Astana",
  la: "Vientiane",
  lb: "Beirut",
  lc: "Castries",
  li: "Vaduz",
  lk: "Sri Jayawardenepura Kotte",
  lr: "Monrovia",
  ls: "Maseru",
  lt: "Vilnius",
  lu: "Luxembourg",
  lv: "Riga",
  ly: "Tripoli",
  ma: "Rabat",
  mc: "Monaco",
  md: "Chisinau",
  me: "Podgorica",
  mg: "Antananarivo",
  mh: "Majuro",
  mk: "Skopje",
  ml: "Bamako",
  mm: "Naypyidaw",
  mn: "Ulaanbaatar",
  mr: "Nouakchott",
  mt: "Valletta",
  mu: "Port Louis",
  mv: "Malé",
  mw: "Lilongwe",
  mx: "Mexico City",
  my: "Kuala Lumpur",
  mz: "Maputo",
  na: "Windhoek",
  ne: "Niamey",
  ng: "Abuja",
  ni: "Managua",
  nl: "Amsterdam",
  no: "Oslo",
  np: "Kathmandu",
  nr: "Yaren",
  nz: "Wellington",
  om: "Muscat",
  pa: "Panama City",
  pe: "Lima",
  pg: "Port Moresby",
  ph: "Manila",
  pk: "Islamabad",
  pl: "Warsaw",
  pt: "Lisbon",
  pw: "Ngerulmud",
  py: "Asunción",
  qa: "Doha",
  ro: "Bucharest",
  rs: "Belgrade",
  ru: "Moscow",
  rw: "Kigali",
  sa: "Riyadh",
  sb: "Honiara",
  sc: "Victoria",
  sd: "Khartoum",
  se: "Stockholm",
  sg: "Singapore",
  si: "Ljubljana",
  sk: "Bratislava",
  sl: "Freetown",
  sm: "San Marino",
  sn: "Dakar",
  so: "Mogadishu",
  sr: "Paramaribo",
  ss: "Juba",
  st: "São Tomé",
  sv: "San Salvador",
  sy: "Damascus",
  sz: "Mbabane",
  td: "N'Djamena",
  tg: "Lomé",
  th: "Bangkok",
  tj: "Dushanbe",
  tl: "Dili",
  tm: "Ashgabat",
  tn: "Tunis",
  to: "Nuku'alofa",
  tr: "Ankara",
  tt: "Port of Spain",
  tv: "Funafuti",
  tw: "Taipei",
  tz: "Dodoma",
  ua: "Kyiv",
  ug: "Kampala",
  us: "Washington, D.C.",
  uy: "Montevideo",
  uz: "Tashkent",
  va: "Vatican City",
  vc: "Kingstown",
  ve: "Caracas",
  vn: "Hanoi",
  vu: "Port Vila",
  ws: "Apia",
  ye: "Sanaa",
  za: "Pretoria",
  zm: "Lusaka",
  zw: "Harare",
};

COUNTRIES.forEach((c) => {
  if (CAPITALS[c.code]) {
    c.capital = CAPITALS[c.code];
  } else {
    console.warn("Missing capital for", c.code);
    c.capital = "Unknown";
  }
});

export const SIMILAR_FLAGS = {
  ro: ["td", "ad", "md"], // Romania -> Chad, Andorra, Moldova
  td: ["ro", "ad", "md"], // Chad -> Romania...
  id: ["mc", "pl", "sg"], // Indonesia -> Monaco, Poland, Singapore
  mc: ["id", "pl", "sg"],
  pl: ["id", "mc", "sg"],
  ie: ["ci", "it"], // Ireland -> Ivory Coast, Italy
  ci: ["ie", "it"],
  nz: ["au", "gb"], // NZ -> Australia, UK
  au: ["nz", "gb"],
  ml: ["gn", "gh"], // Mali -> Guinea, Ghana
  gn: ["ml", "gh", "gw"],
  ve: ["ec", "co"], // Venezuela -> Ecuador, Colombia
  ec: ["ve", "co"],
  co: ["ve", "ec"],
  lu: ["nl", "py", "fr"], // Luxembourg -> Netherlands, Paraguay, France
  nl: ["lu", "py", "fr"],
  hr: ["rs", "si", "sk", "ru"], // Croatia -> Serbia, Slovenia, Slovakia, Russia
  rs: ["hr", "si", "sk", "ru"],
  si: ["hr", "rs", "sk", "ru"],
  sk: ["hr", "rs", "si", "ru"],
  ru: ["si", "sk", "rs"],
  no: ["is", "dk", "fi", "se"], // Nordic Crosses
  is: ["no", "dk", "fi", "se"],
  dk: ["no", "is", "fi", "se"],
  fi: ["no", "is", "dk", "se"],
  se: ["no", "is", "dk", "fi"],
  us: ["lr", "my"], // USA -> Liberia, Malaysia
  lr: ["us", "my", "cl"],
  my: ["us", "lr"],
  cu: ["pr", "ph"], // Cuba -> Puerto Rico (not in list but similar style), Philippines
  cl: ["tx", "lr"], // Chile -> Texas (lol), Liberia
  jp: ["bd", "pw"], // Japan -> Bangladesh, Palau
  bd: ["jp", "pw"],
  tr: ["tn", "pk"], // Turkey -> Tunisia, Pakistan
  tn: ["tr", "pk", "dz"],
  cn: ["vn", "su"], // China -> Vietnam, USSR(hist)
  vn: ["cn", "ma"],
  so: ["vn", "mm"], // Somalia (star)
  qa: ["bh"], // Qatar -> Bahrain
  bh: ["qa"],
  sv: ["ni", "hn", "gt", "ar"], // Central American blue/white
  ni: ["sv", "hn", "gt", "ar"],
  hn: ["sv", "ni", "gt", "ar"],
  gt: ["sv", "ni", "hn", "ar"],
  ar: ["sv", "ni", "hn", "gt", "uy"],
};

export const c = [
  {
    id: "normal",
    name: "Normal",
    description: "Identify the flag shown",
    color: "green",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>`,
  },
  {
    id: "reverse",
    name: "Reverse",
    description: "Find the flag for the country",
    color: "purple",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="21 8 21 21 3 21 3 8"/><line x1="1" y1="3" x2="23" y2="3"/><line x1="12" y1="14" x2="12" y2="21"/></svg>`,
  },
  {
    id: "blitz",
    name: "Blitz",
    description: "Fast-paced timed challenge",
    color: "red",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-yellow-400"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>`,
  },
  {
    id: "hard",
    name: "Hard",
    description: "Type the country name",
    color: "blue",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>`,
  },
  {
    id: "capitals",
    name: "Capitals",
    description: "Guess the capital city",
    color: "green",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"/><path d="M5 21V7l8-4 8 4v14"/><path d="M8 21v-9a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v9"/></svg>`,
  },
  {
    id: "description",
    name: "Description",
    description: "Match description to flag",
    color: "blue",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>`,
  },
  {
    id: "mindfuck",
    name: "Mindfuck",
    description: "Distorted, chaotic flags",
    color: "pink",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.929 2.586a1 1 0 0 1 .485-.485c1.06-.53 2.536 1.414 2.586 2.929A10.003 10.003 0 0 1 12 22a10.003 10.003 0 0 1-10-10c.114-1.06 1.929-1.536 2.929-.586a1 1 0 0 1 .485.485c.53 1.06-1.414 2.536-2.929 2.586a10.003 10.003 0 0 0 14.142 0c-.05-1.515 1.414-3.465 2.929-2.929a1 1 0 0 1 .485.485z"/></svg>`,
  },
];

export const GAME_MODES = [
  {
    id: "normal",
    name: "Normal",
    description: "Identify the flag shown",
    color: "green",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>`,
  },
  {
    id: "reverse",
    name: "Reverse",
    description: "Find the flag for the country",
    color: "purple",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="21 8 21 21 3 21 3 8"/><line x1="1" y1="3" x2="23" y2="3"/><line x1="12" y1="14" x2="12" y2="21"/></svg>`,
  },
  {
    id: "blitz",
    name: "Blitz",
    description: "Fast-paced timed challenge",
    color: "red",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-yellow-400"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>`,
  },
  {
    id: "hard",
    name: "Hard",
    description: "Type the country name",
    color: "blue",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>`,
  },
  {
    id: "capitals",
    name: "Capitals",
    description: "Guess the capital city",
    color: "green",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18"/><path d="M5 21V7l8-4 8 4v14"/><path d="M8 21v-9a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v9"/></svg>`,
  },
  {
    id: "description",
    name: "Description",
    description: "Match description to flag",
    color: "blue",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>`,
  },
  {
    id: "mindfuck",
    name: "Mindfuck",
    description: "Distorted, chaotic flags",
    color: "pink",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.929 2.586a1 1 0 0 1 .485-.485c1.06-.53 2.536 1.414 2.586 2.929A10.003 10.003 0 0 1 12 22a10.003 10.003 0 0 1-10-10c.114-1.06 1.929-1.536 2.929-.586a1 1 0 0 1 .485.485c.53 1.06-1.414 2.536-2.929 2.586a10.003 10.003 0 0 0 14.142 0c-.05-1.515 1.414-3.465 2.929-2.929a1 1 0 0 1 .485.485z"/></svg>`,
  },
];
