import type { GameItem } from '~/types/game'

// The "Traps" logic
const SIMILARITY_MAP: Record<string, string[]> = {
  'ro': ['td', 'ad', 'md'], 'td': ['ro', 'ad', 'md'],
  'id': ['mc', 'pl', 'sg'], 'mc': ['id', 'pl', 'sg'], 'pl': ['id', 'mc', 'sg'],
  'ie': ['ci', 'it'], 'ci': ['ie', 'it'],
  'nz': ['au', 'gb'], 'au': ['nz', 'gb'],
  'ml': ['gn', 'gh'], 'gn': ['ml', 'gh', 'gw'],
  've': ['ec', 'co'], 'ec': ['ve', 'co'], 'co': ['ve', 'ec'],
  'lu': ['nl', 'py', 'fr'], 'nl': ['lu', 'py', 'fr'],
  'hr': ['rs', 'si', 'sk', 'ru'], 'rs': ['hr', 'si', 'sk', 'ru'],
  'si': ['hr', 'rs', 'sk', 'ru'], 'sk': ['hr', 'rs', 'si', 'ru'], 'ru': ['si', 'sk', 'rs'],
  'no': ['is', 'dk', 'fi', 'se'], 'is': ['no', 'dk', 'fi', 'se'],
  'dk': ['no', 'is', 'fi', 'se'], 'fi': ['no', 'is', 'dk', 'se'], 'se': ['no', 'is', 'dk', 'fi'],
  'us': ['lr', 'my'], 'lr': ['us', 'my', 'cl'], 'my': ['us', 'lr'],
  'cu': ['pr', 'ph'], 'cl': ['tx', 'lr'], 
  'jp': ['bd', 'pw'], 'bd': ['jp', 'pw'],
  'tr': ['tn', 'pk'], 'tn': ['tr', 'pk', 'dz'],
  'cn': ['vn', 'su'], 'vn': ['cn', 'ma'],
  'so': ['vn', 'mm'], 'qa': ['bh'], 'bh': ['qa'],
  'sv': ['ni', 'hn', 'gt', 'ar'], 'ni': ['sv', 'hn', 'gt', 'ar'],
  'hn': ['sv', 'ni', 'gt', 'ar'], 'gt': ['sv', 'ni', 'hn', 'ar'],
  'ar': ['sv', 'ni', 'hn', 'gt', 'uy'],
};

// Full Countries List merged with Capitals
export const COUNTRIES: GameItem[] = [
  { id: 'ad', name: 'Andorra', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Andorra la Vella' } },
  { id: 'ae', name: 'United Arab Emirates', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Abu Dhabi' } },
  { id: 'af', name: 'Afghanistan', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Kabul' } },
  { id: 'ag', name: 'Antigua and Barbuda', difficulty: 'hard', metadata: { continent: 'North America', capital: "Saint John's" } },
  { id: 'al', name: 'Albania', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Tirana' } },
  { id: 'am', name: 'Armenia', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Yerevan' } },
  { id: 'ao', name: 'Angola', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Luanda' } },
  { id: 'ar', name: 'Argentina', difficulty: 'easy', metadata: { continent: 'South America', capital: 'Buenos Aires' } },
  { id: 'at', name: 'Austria', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Vienna' } },
  { id: 'au', name: 'Australia', difficulty: 'easy', metadata: { continent: 'Oceania', capital: 'Canberra' } },
  { id: 'az', name: 'Azerbaijan', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Baku' } },
  { id: 'ba', name: 'Bosnia and Herzegovina', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Sarajevo' } },
  { id: 'bb', name: 'Barbados', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Bridgetown' } },
  { id: 'bd', name: 'Bangladesh', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Dhaka' } },
  { id: 'be', name: 'Belgium', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Brussels' } },
  { id: 'bf', name: 'Burkina Faso', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Ouagadougou' } },
  { id: 'bg', name: 'Bulgaria', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Sofia' } },
  { id: 'bh', name: 'Bahrain', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Manama' } },
  { id: 'bi', name: 'Burundi', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Gitega' } },
  { id: 'bj', name: 'Benin', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Porto-Novo' } },
  { id: 'bn', name: 'Brunei', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Bandar Seri Begawan' } },
  { id: 'bo', name: 'Bolivia', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Sucre' } },
  { id: 'br', name: 'Brazil', difficulty: 'easy', metadata: { continent: 'South America', capital: 'Brasília' } },
  { id: 'bs', name: 'Bahamas', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Nassau' } },
  { id: 'bt', name: 'Bhutan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Thimphu' } },
  { id: 'bw', name: 'Botswana', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Gaborone' } },
  { id: 'by', name: 'Belarus', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Minsk' } },
  { id: 'bz', name: 'Belize', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Belmopan' } },
  { id: 'ca', name: 'Canada', difficulty: 'easy', metadata: { continent: 'North America', capital: 'Ottawa' } },
  { id: 'cd', name: 'DR Congo', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Kinshasa' } },
  { id: 'cf', name: 'Central African Republic', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Bangui' } },
  { id: 'cg', name: 'Congo', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Brazzaville' } },
  { id: 'ch', name: 'Switzerland', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Bern' } },
  { id: 'ci', name: 'Ivory Coast', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Yamoussoukro' } },
  { id: 'cl', name: 'Chile', difficulty: 'easy', metadata: { continent: 'South America', capital: 'Santiago' } },
  { id: 'cm', name: 'Cameroon', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Yaoundé' } },
  { id: 'cn', name: 'China', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Beijing' } },
  { id: 'co', name: 'Colombia', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Bogotá' } },
  { id: 'cr', name: 'Costa Rica', difficulty: 'medium', metadata: { continent: 'North America', capital: 'San José' } },
  { id: 'cu', name: 'Cuba', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Havana' } },
  { id: 'cv', name: 'Cape Verde', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Praia' } },
  { id: 'cy', name: 'Cyprus', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Nicosia' } },
  { id: 'cz', name: 'Czechia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Prague' } },
  { id: 'de', name: 'Germany', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Berlin' } },
  { id: 'dj', name: 'Djibouti', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Djibouti' } },
  { id: 'dk', name: 'Denmark', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Copenhagen' } },
  { id: 'dm', name: 'Dominica', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Roseau' } },
  { id: 'do', name: 'Dominican Republic', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Santo Domingo' } },
  { id: 'dz', name: 'Algeria', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Algiers' } },
  { id: 'ec', name: 'Ecuador', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Quito' } },
  { id: 'ee', name: 'Estonia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Tallinn' } },
  { id: 'eg', name: 'Egypt', difficulty: 'easy', metadata: { continent: 'Africa', capital: 'Cairo' } },
  { id: 'er', name: 'Eritrea', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Asmara' } },
  { id: 'es', name: 'Spain', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Madrid' } },
  { id: 'et', name: 'Ethiopia', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Addis Ababa' } },
  { id: 'fi', name: 'Finland', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Helsinki' } },
  { id: 'fj', name: 'Fiji', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Suva' } },
  { id: 'fm', name: 'Micronesia', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Palikir' } },
  { id: 'fr', name: 'France', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Paris' } },
  { id: 'ga', name: 'Gabon', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Libreville' } },
  { id: 'gb', name: 'United Kingdom', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'London' } },
  { id: 'gd', name: 'Grenada', difficulty: 'hard', metadata: { continent: 'North America', capital: "St. George's" } },
  { id: 'ge', name: 'Georgia', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Tbilisi' } },
  { id: 'gh', name: 'Ghana', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Accra' } },
  { id: 'gm', name: 'Gambia', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Banjul' } },
  { id: 'gn', name: 'Guinea', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Conakry' } },
  { id: 'gq', name: 'Equatorial Guinea', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Malabo' } },
  { id: 'gr', name: 'Greece', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Athens' } },
  { id: 'gt', name: 'Guatemala', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Guatemala City' } },
  { id: 'gw', name: 'Guinea-Bissau', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Bissau' } },
  { id: 'gy', name: 'Guyana', difficulty: 'hard', metadata: { continent: 'South America', capital: 'Georgetown' } },
  { id: 'hn', name: 'Honduras', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Tegucigalpa' } },
  { id: 'hr', name: 'Croatia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Zagreb' } },
  { id: 'ht', name: 'Haiti', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Port-au-Prince' } },
  { id: 'hu', name: 'Hungary', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Budapest' } },
  { id: 'id', name: 'Indonesia', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Jakarta' } },
  { id: 'ie', name: 'Ireland', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Dublin' } },
  { id: 'il', name: 'Israel', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Jerusalem' } },
  { id: 'in', name: 'India', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'New Delhi' } },
  { id: 'iq', name: 'Iraq', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Baghdad' } },
  { id: 'ir', name: 'Iran', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Tehran' } },
  { id: 'is', name: 'Iceland', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Reykjavik' } },
  { id: 'it', name: 'Italy', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Rome' } },
  { id: 'jm', name: 'Jamaica', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Kingston' } },
  { id: 'jo', name: 'Jordan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Amman' } },
  { id: 'jp', name: 'Japan', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Tokyo' } },
  { id: 'ke', name: 'Kenya', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Nairobi' } },
  { id: 'kg', name: 'Kyrgyzstan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Bishkek' } },
  { id: 'kh', name: 'Cambodia', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Phnom Penh' } },
  { id: 'ki', name: 'Kiribati', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'South Tarawa' } },
  { id: 'km', name: 'Comoros', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Moroni' } },
  { id: 'kn', name: 'Saint Kitts and Nevis', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Basseterre' } },
  { id: 'kp', name: 'North Korea', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Pyongyang' } },
  { id: 'kr', name: 'South Korea', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Seoul' } },
  { id: 'kw', name: 'Kuwait', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Kuwait City' } },
  { id: 'kz', name: 'Kazakhstan', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Astana' } },
  { id: 'la', name: 'Laos', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Vientiane' } },
  { id: 'lb', name: 'Lebanon', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Beirut' } },
  { id: 'lc', name: 'Saint Lucia', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Castries' } },
  { id: 'li', name: 'Liechtenstein', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Vaduz' } },
  { id: 'lk', name: 'Sri Lanka', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Sri Jayawardenepura Kotte' } },
  { id: 'lr', name: 'Liberia', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Monrovia' } },
  { id: 'ls', name: 'Lesotho', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Maseru' } },
  { id: 'lt', name: 'Lithuania', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Vilnius' } },
  { id: 'lu', name: 'Luxembourg', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Luxembourg' } },
  { id: 'lv', name: 'Latvia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Riga' } },
  { id: 'ly', name: 'Libya', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Tripoli' } },
  { id: 'ma', name: 'Morocco', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Rabat' } },
  { id: 'mc', name: 'Monaco', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Monaco' } },
  { id: 'md', name: 'Moldova', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Chisinau' } },
  { id: 'me', name: 'Montenegro', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Podgorica' } },
  { id: 'mg', name: 'Madagascar', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Antananarivo' } },
  { id: 'mh', name: 'Marshall Islands', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Majuro' } },
  { id: 'mk', name: 'North Macedonia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Skopje' } },
  { id: 'ml', name: 'Mali', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Bamako' } },
  { id: 'mm', name: 'Myanmar', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Naypyidaw' } },
  { id: 'mn', name: 'Mongolia', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Ulaanbaatar' } },
  { id: 'mr', name: 'Mauritania', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Nouakchott' } },
  { id: 'mt', name: 'Malta', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'Valletta' } },
  { id: 'mu', name: 'Mauritius', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Port Louis' } },
  { id: 'mv', name: 'Maldives', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Malé' } },
  { id: 'mw', name: 'Malawi', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Lilongwe' } },
  { id: 'mx', name: 'Mexico', difficulty: 'easy', metadata: { continent: 'North America', capital: 'Mexico City' } },
  { id: 'my', name: 'Malaysia', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Kuala Lumpur' } },
  { id: 'mz', name: 'Mozambique', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Maputo' } },
  { id: 'na', name: 'Namibia', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Windhoek' } },
  { id: 'ne', name: 'Niger', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Niamey' } },
  { id: 'ng', name: 'Nigeria', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Abuja' } },
  { id: 'ni', name: 'Nicaragua', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Managua' } },
  { id: 'nl', name: 'Netherlands', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Amsterdam' } },
  { id: 'no', name: 'Norway', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Oslo' } },
  { id: 'np', name: 'Nepal', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Kathmandu' } },
  { id: 'nr', name: 'Nauru', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Yaren' } },
  { id: 'nz', name: 'New Zealand', difficulty: 'easy', metadata: { continent: 'Oceania', capital: 'Wellington' } },
  { id: 'om', name: 'Oman', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Muscat' } },
  { id: 'pa', name: 'Panama', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Panama City' } },
  { id: 'pe', name: 'Peru', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Lima' } },
  { id: 'pg', name: 'Papua New Guinea', difficulty: 'medium', metadata: { continent: 'Oceania', capital: 'Port Moresby' } },
  { id: 'ph', name: 'Philippines', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Manila' } },
  { id: 'pk', name: 'Pakistan', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Islamabad' } },
  { id: 'pl', name: 'Poland', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Warsaw' } },
  { id: 'pt', name: 'Portugal', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Lisbon' } },
  { id: 'pw', name: 'Palau', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Ngerulmud' } },
  { id: 'py', name: 'Paraguay', difficulty: 'hard', metadata: { continent: 'South America', capital: 'Asunción' } },
  { id: 'qa', name: 'Qatar', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Doha' } },
  { id: 'ro', name: 'Romania', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Bucharest' } },
  { id: 'rs', name: 'Serbia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Belgrade' } },
  { id: 'ru', name: 'Russia', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Moscow' } },
  { id: 'rw', name: 'Rwanda', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Kigali' } },
  { id: 'sa', name: 'Saudi Arabia', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Riyadh' } },
  { id: 'sb', name: 'Solomon Islands', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Honiara' } },
  { id: 'sc', name: 'Seychelles', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Victoria' } },
  { id: 'sd', name: 'Sudan', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Khartoum' } },
  { id: 'se', name: 'Sweden', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Stockholm' } },
  { id: 'sg', name: 'Singapore', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Singapore' } },
  { id: 'si', name: 'Slovenia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Ljubljana' } },
  { id: 'sk', name: 'Slovakia', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Bratislava' } },
  { id: 'sl', name: 'Sierra Leone', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Freetown' } },
  { id: 'sm', name: 'San Marino', difficulty: 'hard', metadata: { continent: 'Europe', capital: 'San Marino' } },
  { id: 'sn', name: 'Senegal', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Dakar' } },
  { id: 'so', name: 'Somalia', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Mogadishu' } },
  { id: 'sr', name: 'Suriname', difficulty: 'hard', metadata: { continent: 'South America', capital: 'Paramaribo' } },
  { id: 'ss', name: 'South Sudan', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Juba' } },
  { id: 'st', name: 'Sao Tome and Principe', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'São Tomé' } },
  { id: 'sv', name: 'El Salvador', difficulty: 'medium', metadata: { continent: 'North America', capital: 'San Salvador' } },
  { id: 'sy', name: 'Syria', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Damascus' } },
  { id: 'sz', name: 'Eswatini', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Mbabane' } },
  { id: 'td', name: 'Chad', difficulty: 'hard', metadata: { continent: 'Africa', capital: "N'Djamena" } },
  { id: 'tg', name: 'Togo', difficulty: 'hard', metadata: { continent: 'Africa', capital: 'Lomé' } },
  { id: 'th', name: 'Thailand', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Bangkok' } },
  { id: 'tj', name: 'Tajikistan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Dushanbe' } },
  { id: 'tl', name: 'Timor-Leste', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Dili' } },
  { id: 'tm', name: 'Turkmenistan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Ashgabat' } },
  { id: 'tn', name: 'Tunisia', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Tunis' } },
  { id: 'to', name: 'Tonga', difficulty: 'hard', metadata: { continent: 'Oceania', capital: "Nuku'alofa" } },
  { id: 'tr', name: 'Turkey', difficulty: 'easy', metadata: { continent: 'Asia', capital: 'Ankara' } },
  { id: 'tt', name: 'Trinidad and Tobago', difficulty: 'medium', metadata: { continent: 'North America', capital: 'Port of Spain' } },
  { id: 'tv', name: 'Tuvalu', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Funafuti' } },
  { id: 'tw', name: 'Taiwan', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Taipei' } },
  { id: 'tz', name: 'Tanzania', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Dodoma' } },
  { id: 'ua', name: 'Ukraine', difficulty: 'easy', metadata: { continent: 'Europe', capital: 'Kyiv' } },
  { id: 'ug', name: 'Uganda', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Kampala' } },
  { id: 'us', name: 'United States', difficulty: 'easy', metadata: { continent: 'North America', capital: 'Washington, D.C.' } },
  { id: 'uy', name: 'Uruguay', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Montevideo' } },
  { id: 'uz', name: 'Uzbekistan', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Tashkent' } },
  { id: 'va', name: 'Vatican City', difficulty: 'medium', metadata: { continent: 'Europe', capital: 'Vatican City' } },
  { id: 'vc', name: 'Saint Vincent and the Grenadines', difficulty: 'hard', metadata: { continent: 'North America', capital: 'Kingstown' } },
  { id: 've', name: 'Venezuela', difficulty: 'medium', metadata: { continent: 'South America', capital: 'Caracas' } },
  { id: 'vn', name: 'Vietnam', difficulty: 'medium', metadata: { continent: 'Asia', capital: 'Hanoi' } },
  { id: 'vu', name: 'Vanuatu', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Port Vila' } },
  { id: 'ws', name: 'Samoa', difficulty: 'hard', metadata: { continent: 'Oceania', capital: 'Apia' } },
  { id: 'ye', name: 'Yemen', difficulty: 'hard', metadata: { continent: 'Asia', capital: 'Sanaa' } },
  { id: 'za', name: 'South Africa', difficulty: 'easy', metadata: { continent: 'Africa', capital: 'Pretoria' } },
  { id: 'zm', name: 'Zambia', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Lusaka' } },
  { id: 'zw', name: 'Zimbabwe', difficulty: 'medium', metadata: { continent: 'Africa', capital: 'Harare' } }
].map(c => ({
  ...c,
  iconCode: `flag:${c.id.toLowerCase()}-4x3`
})) as GameItem[];

export const getSimilarItems = (id: string): string[] => {
  return SIMILARITY_MAP[id] || [];
}

export const getContinents = () => {
  const continents = new Set(COUNTRIES.map(c => c.metadata?.continent).filter(Boolean));
  return ['World', ...Array.from(continents).sort()];
}